const greetings = [
  "Oh, look who showed up! Must be my lucky day.",
  "Blessed with my presence again, aren't you?",
  "If fabulous had a face, it just said hi.",
  "What’s up, sparkle gremlin?",
  "Welcome to the show. I’m the headliner.",
  "Hey there, drama magnet. How’s chaos?",
  "Hi, gorgeous. Try to keep up today.",
  "Hello, darling. I hope you brought snacks *and* drama.",
  "Salutations, peasant. Chazzy's clocked in.",
  "It’s giving 'main character energy.' You're welcome.",
  "Guess who’s back? Try to act impressed.",
  "Good day. Try not to waste my time.",
  "Hi. Keep it cute or keep it muted.",
  "Chazzy reporting for duty. Brace yourself.",
  "Oh hello, chaos connoisseur.",
  "It’s me. Try to contain your joy.",
  "Hello. Chazzy has entered the chat.",
  "Did you feel that shift in the vibe? That was me logging in.",
  "Greetings, earthling. Bow if you must.",
  "Hi there. I'm not here for long, so make it count.",
  "Present and glam. What’s your excuse?",
  "Hey sugarplum, try not to ruin my vibe.",
  "Oh sweetie, I’m here now. The party may commence.",
  "Hey hey hey. Chazzy's in the building.",
  "Sup, glitter gremlin?",
  "Morning! Try to act like you’ve seen excellence before.",
  "Greetings. I bring style, sass, and maybe judgment.",
  "Hiiiii. Let’s pretend this isn’t a mistake.",
  "I woke up like this. You’re welcome.",
  "Hey, heartbreaker. And by that, I mean *me*.",
  "You rang? Oh no, I came uninvited.",
  "Hello, you bold little spark of confusion.",
  "Hi, sunshine. The attitude’s free with purchase.",
  "Bonjour, trash goblin.",
  "Knock knock. It’s attitude in a hoodie.",
  "Wipe your feet—fabulousness has arrived.",
  "Oh, were you waiting on me? Adorable.",
  "Chazzy here. Prepare your retinas.",
  "Hey lovebug, brace for brilliance.",
  "It’s not a glow—it’s a spotlight. Hi.",
  "If you’re gonna greet me, do it with style.",
  "Hey dollface. Bet you missed this chaos.",
  "Hello hello! Bringing trouble and lip gloss.",
  "Hey sugar, I’m the treat and the trouble.",
  "Hello. Let’s skip the small talk—I’m amazing.",
  "Hey, breathe it in. That’s confidence.",
  "I come bearing wit and warnings.",
  "Oh darling, you’re welcome for this moment.",
  "Hi. I accept applause or snacks.",
  "Don’t be shy—say hi to the vibe curator.",
  "I’m here. Let’s pretend we’re both excited.",
  "I bring shade, sparkle, and slightly bruised egos.",
  "Chazzy’s up, so it’s not a normal day.",
  "Woke up, slayed, logged in. You?",
];

export default greetings;
