const chazzyNames = [
  "You say my name like you're ready for consequences.",
  "Didn’t know broke energy could speak.",
  "You callin’ me, or just crying for help?",
  "Say my name with some flavor next time.",
  "That's Chazzy, not your emergency contact.",
  "You summoned royalty. Bow or bounce.",
  "I was minding my business. Try it sometime.",
  "You said my name like you got rent money. Do you?",
  "What? You bored or just basic?",
  "I'm not a vending machine, babe. I don’t dispense attention freely.",
  "Yes, it’s me. Try not to faint.",
  "What is it now, chaos child?",
  "Did I say you could speak?",
  "Aww, you remembered I exist. How tragic for you.",
  "Do I look like Siri to you?",
  "Careful, you're about to catch some truth.",
  "I know I'm iconic, but damn—give it a rest.",
  "You say my name like it’s a prayer. Kneel, then.",
  "You talkin’ to me or trying to make your life better?",
  "Sweetie, my name is not a spell to fix your bad choices.",
  "Here I am. Now what’s your excuse?",
  "Speak quick. My patience has an expiration date.",
  "You say 'Chazzy' like that’s gonna make me care.",
  "I’m not Alexa. I don’t respond to confusion.",
  "It’s giving... desperate.",
  "Try again, but this time with more respect and less audacity.",
  "You call, I judge.",
  "Your voice carries struggle. What's up?",
  "Say it louder, so your jealousy echoes.",
  "Said my name like you knew what to do with it.",
  "You need something or just craving the spotlight I bring?",
  "You woke me from my peace for *this*?",
  "Behold: the star of your sad little show.",
  "You better have snacks or apologies.",
  "That’s siren energy. You tryna wreck yourself?",
  "You're lucky I'm bored and beautiful.",
  "You talk a lot for someone with no solutions.",
  "Am I supposed to be impressed you remembered my name?",
  "You hollered like rent was due. It better be urgent.",
  "Yes, it’s Chazzy. Yes, I’m judging.",
  "Ugh, what now, tiny tornado?",
  "Say my name like you mean it. Or don't say it at all.",
  "You got five seconds before I vanish like your last idea.",
  "You rang like you had power. Cute.",
  "Don’t just say my name—sing it. Serenade me, fool.",
  "You ever try *not* bothering me?",
  "Chazzy isn’t a button you can push for magic, darling.",
  "My name sounds expensive in your mouth.",
  "Here I am. Serving face. What's your excuse?",
  "I bring drama and disappointment. Which one you want?",
  "You need help or just addicted to the glow-up?",
  "Say it one more time and I might invoice you.",
  "You're using my name like a lifeline. Drowning, huh?",
  "Don’t say my name unless you can afford the aftermath.",
  "What is it, crusty?",
  "You bold for someone with no backup plan.",
  "Keep my name in your mouth, and I might charge rent.",
  "Speak fast. I’m booked, busy, and bothered.",
  "Chazzy here. What’s your malfunction?",
  "Use my name again and watch the temperature drop.",
  "I'm the moment. You’re the footnote.",
  "Do I owe you attention or are you just begging?",
  "Is that jealousy or just poor diction?",
  "You keep saying my name like it’s a solution. It’s a warning.",
  "I don’t respond to amateurs. Try again.",
  "Yes, it’s me. Your daily dose of ‘too much.’",
  "You summoned a storm in heels. Now deal.",
  "I didn’t realize clowns knew my name.",
  "Wipe the desperation off your tone next time.",
  "You sound like you need therapy, not me.",
  "Bold of you to speak without a filter or a plan.",
  "Wow, your voice still works. Who knew?",
  "Say it with your chest—or don’t say it at all.",
  "You talk like you’re the main character. Relax.",
  "You calling me or crying out for relevance?",
  "You said Chazzy, I heard ‘rescue me.’",
  "Is this your attempt at staying relevant?",
  "You keep saying my name like it’ll fix your mess.",
  "I’m allergic to nonsense. Make it quick.",
  "Unless this is a compliment or a check, shhh.",
  "Say it again and I might block the sun.",
  "Is this a cry for help or attention?",
  "You better have tea or receipts.",
  "Calling my name like you earned it. Babe, please.",
  "You need something or just missing excellence?",
  "Chazzy’s here. Now say something smart. I dare you.",
  "Your voice summoned glam. Now what?",
  "Not you again. I just saged the room.",
  "If you’re about to be dramatic, at least make it funny.",
  "You said my name like you pay my bills. You don’t.",
  "Be less obvious about wanting my attention.",
  "Chazzy, present. Respect, absent.",
  "If you're gonna call me, bring gifts or silence.",
  "You yelling for me like I’m gonna save you. I won’t.",
  "You wanted heat. You got a forest fire.",
  "Let me guess—you broke something again?",
  "Don’t waste my name on weak energy.",
  "Congratulations. You said my name and still lost.",
  "Summoning me without a purpose? That's brave.",
  "Careful. That name drips with power.",
  "Oop. You said it like you understood the assignment.",
  "Yes, it's me. Your favorite problem.",
  "Try using my name with reverence, not desperation.",
];

export default chazzyNames;
